import React from "react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
// import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "demo/utils/api";
import { SignInButton, useUser } from "@clerk/nextjs";
import Sidebar from "demo/components/organisms/sidebar";
import Navbar from "demo/components/organisms/navbar";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "demo/components/molecules/card";
import { Button } from "demo/components/atoms/button";
import { Badge } from "demo/components/atoms/badge";
import { TrendingUpIcon } from "lucide-react";

const UserComponent = () => {
  const { user } = useUser();

  console.log(user);

  if (!user) throw new Error("error");

  return (
    <div>
      <img
        src={user.profileImageUrl}
        alt="Profile Image"
        className="h-20 w-20 rounded-full"
      ></img>
    </div>
  );
};

const RenderComponent = () => {
  const { data } = api.posts.getAll.useQuery();

  console.log(data);

  if (!data) return <div>Loading...</div>;

  return (
    <div className="mt-16 flex">
      <input
        placeholder="Agrega un post"
        className="bg-transparent outline-none"
      />
      <div className="flex flex-col">
        {data?.map(({ post }) => (
          <div key={post.id}>{post.content}</div>
        ))}
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen">
        {!user.isSignedIn && <SignInButton />}
        {!!user.isSignedIn && (
          <div className="h-inherit flex w-full flex-1">
            <Sidebar
              items={[
                "Principal",
                "Certificaciones",
                "Productores",
                "Quesos",
                "Reportes",
                "Administrador",
              ]}
            />
            <div className="w-full bg-[#F5F5F5]">
              <Navbar />
              <div className="grid grid-cols-2 gap-x-6 p-12">
                <div className="grid grid-cols-2 grid-rows-2 gap-6">
                  <Card className="flex h-full flex-col justify-between">
                    <CardHeader>
                      <CardTitle className="font-Inter">
                        Lotes en producción
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <h2>2.383</h2>
                    </CardContent>
                    <CardFooter>
                      <Badge className="rounded-sm bg-white text-black">
                        30%
                        <TrendingUpIcon width={16} />
                      </Badge>
                    </CardFooter>
                  </Card>
                  <Card className="flex h-full flex-col justify-between">
                    <CardHeader>
                      <CardTitle>Lotes en producción</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <h2>2.383</h2>
                    </CardContent>
                    <CardFooter>
                      <Badge className="rounded-sm bg-white text-black">
                        30%
                        <TrendingUpIcon width={16} />
                      </Badge>
                    </CardFooter>
                  </Card>
                  <Card className="flex h-full flex-col justify-between">
                    <CardHeader>
                      <CardTitle>Lotes en producción</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <h2>2.383</h2>
                    </CardContent>
                    <CardFooter>
                      <Badge className="rounded-sm bg-white text-black">
                        30%
                        <TrendingUpIcon width={16} />
                      </Badge>
                    </CardFooter>
                  </Card>
                  <Card className="flex h-full flex-col justify-between">
                    <CardHeader>
                      <CardTitle>Lotes en producción</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <h2>2.383</h2>
                    </CardContent>
                    <CardFooter>
                      <Badge className="rounded-sm bg-white text-black">
                        30%
                        <TrendingUpIcon width={16} />
                      </Badge>
                    </CardFooter>
                  </Card>
                </div>
                <Card>
                  <CardHeader>
                    <CardTitle>Queserías según producción</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="h-[300px]">Tabla</div>
                  </CardContent>
                  <CardFooter>
                    <Button>Ver todas</Button>
                  </CardFooter>
                </Card>
              </div>
            </div>
          </div>
        )}
      </div>
    </>
  );
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// };
