import React, { useEffect } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "utils/api";
import { SignOutButton, useClerk, useUser } from "@clerk/nextjs";

const UserComponent = () => {
  const { user } = useUser();

  console.log(user);

  if (!user) throw new Error("error");

  return (
    <div>
      <img
        src={user.profileImageUrl}
        alt="Profile Image"
        className="h-20 w-20 rounded-full"
      ></img>
    </div>
  );
};

const RenderComponent = () => {
  const { data } = api.posts.getAll.useQuery();

  console.log(data);

  if (!data) return <div>Loading...</div>;

  return (
    <div className="mt-16 flex">
      <input
        placeholder="Agrega un post"
        className="bg-transparent outline-none"
      />
      <div className="flex flex-col">
        {data?.map(({ post }) => (
          <div key={post.id}>{post.content}</div>
        ))}
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const { isSignedIn } = useUser();
  const { openSignIn } = useClerk();

  useEffect(() => {
    if (!isSignedIn) {
      openSignIn();
    }
  }, [isSignedIn]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!!isSignedIn && <div></div>}
    </>
  );
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// };
